### ISSUE TITLE
P2p code review

### ISSUE THREAD

**Issue by nyatindopatrick** [hillarioh/TIC-TAC-TOE-JS#2]
Please leave some comments

**Comment by dili021** [comment]
Good job with utilizing ES6! I caught 2 errors:
- A draw game just did nothing when ended
- A won game took me back to player name input which is not in line with the last feature specified in the readme: 

![image](https://user-images.githubusercontent.com/55356496/88770471-2b413680-d17e-11ea-8c02-377e0508464a.png)

Other than that, great work!
